version: '3.1'
services:
  db:
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_USER: tina4
      MYSQL_PASSWORD: Password1234
      MYSQL_DATABASE: tina4
    ports:
      - "5508:3306"
